class error_message:
    NO_AUTHENTICATION = 'NO_AUTHENTICATION'
    NOT_FOUND = 'NOT_FOUND'
    UNAUTHORIZED = 'UNAUTHORIZED'
    CHANNEL_CLOSED = 'CHANNEL_CLOSED'
    CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND'
    UNSUPPORTED_METHOD = 'UNSUPPORTED_METHOD'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
